project:
  type: website
  output-dir: docs

website:
  title: "Democratizing Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd  # Ensure that each menu item has both 'text' and 'href' keys for clarity

format:
  html:
    theme: cosmo
    css: custom-styles.css
    toc: true
    favicon: favicon.ico  # Adding a favicon

# Additional global options
editor_options:
  chunk_output_type: console